title   MacronLinux — En mARCH! (fallback initramfs)
linux   /%INSTALL_DIR%/boot/x86_64/vmlinuz-linux
initrd  /%INSTALL_DIR%/boot/x86_64/initramfs-linux-fallback.img
options archisobasedir=%INSTALL_DIR% archisolabel=%ARCHISO_LABEL%
