#
# /etc/pacman.conf — MacronLinux
#
# Dépôts officiels Arch Linux pour mkarchiso
#

[options]
HoldPkg      = pacman glibc
Architecture = auto

# Vérification des signatures
SigLevel    = Never
LocalFileSigLevel = Optional

# Téléchargements parallèles
ParallelDownloads = 5

#
# DÉPÔTS
#

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

# Décommentez pour activer le dépôt multilib (applications 32 bits)
#[multilib]
#Include = /etc/pacman.d/mirrorlist
