HOOKS=(base udev microcode modconf kms memdisk archiso archiso_pxe_common archiso_pxe_nbd archiso_pxe_http archiso_pxe_nfs block filesystems keyboard)
COMPRESSION="gzip"
COMPRESSION_OPTIONS=()
MODULES_DECOMPRESS="yes"
